### ISSUE TITLE
scrapy puppeteer sends a post request to scrapy puppeteer service api for goto

### ISSUE THREAD

**Issue by gsudhanshu** [ispras/scrapy-puppeteer#3]
Error:

ERROR: Spider error processing <POST http://localhost:3000/goto> (referer: None)

Spider code:

import scrapy
from scrapypuppeteer import PuppeteerRequest

class QuotesjsSpider(scrapy.Spider):
    name = 'quotesjs'

    def start_requests(self):
        yield PuppeteerRequest('http://quotes.toscrape.com/js/', close_page=False, callback=self.parse)

    def parse(self, response):
        for quote in response.css('div.quote').getall():
            yield {
                "Quote" : quote.css('span.text::text').get(),
                "Author" : quote.css('small.author::text').get(),
                "Tags" : quote.css('a.tag::text').getall()
            }

**Comment by mxsnq** [comment]
I couldn't reproduce the issue. Have you started the [service](https://github.com/ispras/scrapy-puppeteer-service) on `localhost:3000`? Can you run your spider again with LOG_LEVEL=DEBUG setting and attach full log? Only error I have is with parsing: you don't need `.getall()` in `for quote in response.css('div.quote').getall():`, it results in `quote` being string with element html.

**Comment by gsudhanshu** [comment]
Thanks, issue resolved
